# Generated by Django 5.1.2 on 2025-02-02 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="online_user_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_room_set",
                through="chat.RoomMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_room_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
