# Generated by Django 5.1.2 on 2024-12-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-pk"]},
        ),
    ]
